export const SET_SINGLE_LINE = 'SET_SINGLE_LINE'
export const UPDATE_SINGLE_PAYMENT = 'UPDATE_SINGLE_PAYMENT'
export const TOTAL_PAY = 'TOTAL_PAY'
// export const UPDATE_FAVOURITE = 'UPDATE_FAVOURITE'
