export const SET_SINGLE_LINE = 'SET_SINGLE_LINE'
export const UPDATE_SINGLE_PAYMENT = 'UPDATE_SINGLE_PAYMENT'
export const UPDATE_DATE = 'UPDATE_DATE'
export const UPDATE_FROM_LOCAL = 'UPDATE_FROM_LOCAL'
